name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm globally
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate static site
        run: pnpm run generate

      - name: Create www directory
        run: mkdir -p www
      
      - name: Copy files to www
        run: cp -r .output/public/* www/

      - name: Add Android platform (if not already added)
        run: npx cap add android || echo "Android platform already added"

      - name: Copy assets to Android project
        run: npx cap copy android

      - name: Setup Java environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build APK with Gradle
        working-directory: android
        run: ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
